### PR TITLE
BFI Test Scenarios

### LINKED ISSUE #186: BFI bugs
However, `suppressCombinations` doesn't work and the UX is also busted. If I run that above with `suppressCombinations` on, I see it run tests anyway where combinations are present and faults are not rendered correctly.

I suggest adding additional tests to cover the following scenarios:

1. GRPC before and after Redis, with no fault injection for GRPC to simulate BFI interaction with other RPCs before/after with no fault injection.
2. Variant of 1 with GRPC fault injection as well.
3. Multiple Redis calls with BFI with and without combination suppression.
4. dataNondeterminism = true variant of all three.
5. set hasNext = false in initial accumulator
6. BFS and DFS scheduling with BFI

### PR DESCRIPTION
**Pull request by MichaelA-ops**
Closes #186

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
Changed the base, too hard to review when it contains the contents from the other PR.

File: src/test/java/cloud/filibuster/functional/java/redis/scenarios/JUnitFaultyRedisFaultFreeGRPCTest.java [hunk 1]
```diff
@@ -0,0 +1,180 @@
...
+import static cloud.filibuster.integration.instrumentation.TestHelper.startHelloServerAndWaitUntilAvailable;
+import static cloud.filibuster.integration.instrumentation.TestHelper.stopHelloServerAndWaitUntilUnavailable;
+import static cloud.filibuster.junit.Assertions.wasFaultInjected;
+import static cloud.filibuster.junit.Assertions.wasFaultInjectedOnMethod;
+import static org.junit.jupiter.api.Assertions.assertEquals;
+import static org.junit.jupiter.api.Assertions.assertTrue;
+
+@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
+@SuppressWarnings("unchecked")
+public class JUnitFaultyRedisFaultFreeGRPCTest extends JUnitAnnotationBaseTest {
```
Comment (cmeiklejohn) [inline src/test/java/cloud/filibuster/functional/java/redis/scenarios/JUnitFaultyRedisFaultFreeGRPCTest.java:46]: Why is this test called "fault-free"?  I don't get it -- it's injecting exceptions, transforming responses, etc.

Comment (MichaelA-ops) [reply src/test/java/cloud/filibuster/functional/java/redis/scenarios/JUnitFaultyRedisFaultFreeGRPCTest.java:46]: It corresponds to the first scenario mentioned in #186

Comment (cmeiklejohn) [reply src/test/java/cloud/filibuster/functional/java/redis/scenarios/JUnitFaultyRedisFaultFreeGRPCTest.java:46]: Got it!

**Comment by cmeiklejohn** [comment]
#186 also mentioned the broken UX -- is that fixed in here too? (Since, closing/merging this will close that issue.)

File: src/test/java/cloud/filibuster/functional/java/redis/scenarios/JUnitFaultyRedisFaultFreeGRPCTest.java [hunk 2]
```diff
@@ -0,0 +1,180 @@
...
+
+        startHelloServerAndWaitUntilAvailable();
+    }
+
+    @AfterAll
+    public static void stopAllServices() throws InterruptedException {
+        stopHelloServerAndWaitUntilUnavailable();
+    }
+
+    @DisplayName("Tests whether Redis sync interceptor connection can read and write")
```
Comment (cmeiklejohn) [inline src/test/java/cloud/filibuster/functional/java/redis/scenarios/JUnitFaultyRedisFaultFreeGRPCTest.java:82]: Perhaps it would make this easier to read/review if these test names were more descriptive: like, for example, test fault-free Redis with GRPC request before to verify ... etc.  Right now, it's unclear from a high-level what test is doing what

Comment (cmeiklejohn) [reply src/test/java/cloud/filibuster/functional/java/redis/scenarios/JUnitFaultyRedisFaultFreeGRPCTest.java:82]: (the test name is the same across multiple files, it's difficult to review, etc.)

**Comment by MichaelA-ops** [comment]
Hi @cmeiklejohn, should be fixed now

File: src/main/java/cloud/filibuster/junit/configuration/examples/db/redis/FaultyHasNextFalseRedisTransformStringAnalysisConfigurationFile.java [hunk 3]
```diff
@@ -0,0 +1,29 @@
+package cloud.filibuster.junit.configuration.examples.db.redis;
+
+import cloud.filibuster.junit.configuration.FilibusterAnalysisConfiguration;
+import cloud.filibuster.junit.configuration.FilibusterAnalysisConfigurationFile;
+import cloud.filibuster.junit.configuration.FilibusterCustomAnalysisConfigurationFile;
+import cloud.filibuster.junit.server.core.transformers.FaultyStringTransformerWithFalseHasNext;
+
+public class FaultyHasNextFalseRedisTransformStringAnalysisConfigurationFile implements FilibusterAnalysisConfigurationFile {
```
Comment (cmeiklejohn) [inline src/main/java/cloud/filibuster/junit/configuration/examples/db/redis/FaultyHasNextFalseRedisTransformStringAnalysisConfigurationFile.java:8]: Nitpick: is it possible to put the faulty/test configurations that no one should use under test/ and not main/?

Comment (MichaelA-ops) [reply src/main/java/cloud/filibuster/junit/configuration/examples/db/redis/FaultyHasNextFalseRedisTransformStringAnalysisConfigurationFile.java]: Gotcha

**Review by cmeiklejohn — APPROVED** [review]
