### PR TITLE
Redis connection interceptor

### LINKED ISSUE #99: Investigate how the FilibusterClientInteceptor works for GRPC

### LINKED ISSUE #102: Working prototype for exception injection
Using lettuce interposition, inject exceptions using Filibuster that throw errors.

This should cause your test to fail, if your test fails to handle these errors when the cache is primed.

### PR DESCRIPTION
**Pull request by MichaelA-ops**
resolves #99, #100. #101

### CODE REVIEW

File: src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/LettuceInterceptor.java [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+    public static boolean isFaultInjected = false;
+
+    public LettuceInterceptor(StatefulRedisConnection<String, String> redisConnection) {
+        this.redisConnection = redisConnection;
+    }
+
+    @Override
+    public Object invoke(MethodInvocation invocation) throws Throwable {
+        if (isFaultInjected) {
+            throw new Exception("An exception was thrown at LettuceInterceptor");
```
Comment (cmeiklejohn) [inline src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/LettuceInterceptor.java:21]: You'll want this to be a specific exception type that Lettuce throws, right?

File: src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/LettuceInterceptor.java [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+
+import io.lettuce.core.api.StatefulRedisConnection;
+import io.lettuce.core.dynamic.intercept.MethodInterceptor;
+import io.lettuce.core.dynamic.intercept.MethodInvocation;
+
+
+
+public class LettuceInterceptor implements MethodInterceptor {
+
+    private final StatefulRedisConnection<String, String> redisConnection; //Will be needed later when data failures are injected
```
Comment (cmeiklejohn) [inline src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/LettuceInterceptor.java:11]: What does this comment mean?

File: src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/LettuceInterceptedConnection.java [hunk 3]
```diff
@@ -0,0 +1,17 @@
...
+import io.lettuce.core.dynamic.intercept.DefaultMethodInvokingInterceptor;
+import io.lettuce.core.dynamic.intercept.InvocationProxyFactory;
+
+public abstract class LettuceInterceptedConnection {
+
+    public static MyRedisCommands create (StatefulRedisConnection<String, String> redisConnection) {
+        InvocationProxyFactory myFactory = new InvocationProxyFactory();
+        myFactory.addInterface(MyRedisCommands.class);
+        myFactory.addInterceptor(new DefaultMethodInvokingInterceptor());
+        myFactory.addInterceptor(new LettuceInterceptor(redisConnection));
```
Comment (cmeiklejohn) [inline src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/LettuceInterceptedConnection.java:13]: What's the use for the two interceptors?

File: src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/LettuceInterceptor.java (hunk 1 above)
Comment (MichaelA-ops) [reply src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/LettuceInterceptor.java:21]: Yes

File: src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/MyRedisCommands.java [hunk 4]
```diff
@@ -0,0 +1,8 @@
+package cloud.filibuster.instrumentation.libraries.lettuce;
+
+import io.lettuce.core.dynamic.Commands;
+
+public interface MyRedisCommands extends Commands {
+    String get(String key); // Synchronous Execution of GET
+    String set(String key, String value); // asynchronous SET execution
```
Comment (cmeiklejohn) [inline src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/MyRedisCommands.java]: Do you need to have the full API implemented here?

File: src/test/java/cloud/filibuster/functional/java/redis/JUnitRedisAccessTest.java [hunk 5]
```diff
@@ -14,7 +17,7 @@
 
 import static cloud.filibuster.integration.instrumentation.TestHelper.*;
 import static cloud.filibuster.junit.Assertions.*;
-import static org.junit.jupiter.api.Assertions.assertEquals;
+import static org.junit.jupiter.api.Assertions.*;
```
Comment (cmeiklejohn) [inline src/test/java/cloud/filibuster/functional/java/redis/JUnitRedisAccessTest.java:20]: Please change your editor configuration to not use wildcard imports.

File: src/test/java/cloud/filibuster/functional/java/redis/JUnitRedisAccessTest.java [hunk 6]
```diff
@@ -54,4 +58,35 @@ public void testRedisHello() {
...
+
+    @Test
+    @DisplayName("Tests whether Redis interceptor can inject an exception")
+    @Order(2)
+    public void testRedisInterceptedExceptionThrowing() {
+        MyRedisCommands myRedisCommands = LettuceInterceptedConnection.create(redisConnection);
+        LettuceInterceptor.isFaultInjected = true;
+        String key = "test";
+        String value = "example";
+        try {
```
Comment (cmeiklejohn) [inline src/test/java/cloud/filibuster/functional/java/redis/JUnitRedisAccessTest.java:70]: You should be using assertThrows here instead of a manual try/catch.  (You also can do `expected=` in the `@Test` annotation.)

**Review by cmeiklejohn — CHANGES_REQUESTED** [review]

File: src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/MyRedisCommands.java (hunk 4 above)
Comment (MichaelA-ops) [reply src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/MyRedisCommands.java]: Just the signatures, yes

File: src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/LettuceInterceptor.java (hunk 2 above)
Comment (MichaelA-ops) [reply src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/LettuceInterceptor.java:11]: For byzentine fault injections, I will need to have redisConnection as an attibute in the LettuceInterceptor class

File: src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/MyRedisCommands.java (hunk 4 above)
Comment (MichaelA-ops) [reply src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/MyRedisCommands.java]: Not necessary anymore, I switched to the Lettuce interface RedisCommands

**Review by cmeiklejohn — APPROVED** [review]
looks great!
